services:
  solarthing:
    image: 'ghcr.io/wildmountainfarms/solarthing:latest'
    container_name: solarthing-main
    restart: 'unless-stopped'
    command: run --base config/base.json
    group_add: # this is only necessary if you are using a user other than root
      - dialout
    cap_add:
      - SYS_RAWIO
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
    volumes:
#      This is to work in HASSIO with the Portainer add in.
#      Note you must manually copy the config file to this directory in HASSIO
#      - '/mnt/data/supervisor/share/solarthing/config:/app/config:ro'
#      Below is for normal docker operation
       - './config:/app/config:ro'
